const {AssertionError} = require('node:assert');

throw new AssertionError({
    message: "Valid exceptions"
});
