throw {
    name: "AssertionError",
    message: "Valid exceptions"
}
