throw {
    "name": "AssertionError",
    "boodschap": "Valid exceptions"
};

